name: Android CI

on: [ push, pull_request ]

jobs:
  build:
    env: 
      VARIANT: release
      PROJECT_LOCATION: src/android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: deps
      run: |
        sudo apt-get -y update
        sudo apt-get -y install apksigner

    - name: Build with Gradle
      working-directory: ${{ env.PROJECT_LOCATION }}
      run: |
        ./gradlew bundle${{ env.VARIANT }}
        ./gradlew assemble${{ env.VARIANT }}
                
    - if: github.repository == 'SachinVin/citra-android'
      name: Sign apk
      env:
         KEYSTORE_PASS: ${{ secrets.keystore_pass }}
         KEY_ALIAS: 'dummy'
         KEY_PASS: ${{ secrets.key_pass }}
      run: |
        apksigner sign --verbose --ks dummy.jks --ks-pass env:KEYSTORE_PASS --ks-key-alias ${{ env.KEY_ALIAS }} --key-pass env:KEY_PASS \
          ${{ env.PROJECT_LOCATION }}/app/build/outputs/apk/${{ env.VARIANT }}/app-${{ env.VARIANT }}.apk

    - name: Deploy on Github        
      uses: actions/upload-artifact@v2
      with:
        name: citra-android-${{ env.VARIANT }}-${{ github.sha }}
        path: ${{ env.PROJECT_LOCATION }}/app/build/outputs/apk/${{ env.VARIANT }}/app-${{ env.VARIANT }}.apk
