name: Android CI

on: [ push, pull_request ]

jobs:
  build:
    env: 
      flavour: release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

#    - name: deps
#      run: |
#        sudo apt-get -y update
#        sudo apt-get -y install apksigner
#        echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Build with Gradle
      working-directory: src/android
      run: |
        ./gradlew bundleRelease
        ./gradlew assembleRelease
                
    - if: github.repository == 'SachinVin/citra-android'
      name: Sign apk
      env:
         keystore_pass: ${{ secrets.keystore_pass }}
         key_pass: ${{ secrets.key_pass }}
      run: |
        apksigner sign --verbose --ks dummy.jks --ks-pass env:keystore_pass --key-pass env:key_pass \
          src/android/app/build/outputs/apk/${{ env.flavour }}/app-${{ env.flavour }}.apk

    - name: Deploy on Github        
      uses: actions/upload-artifact@v2
      with:
        name: citra-android-${{ env.flavour }}-${{ github.sha }}
        path: src/android/app/build/outputs/apk/${{ env.flavour }}/app-${{ env.flavour }}.apk
